server:
  port: 8081

spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: jggen0121@naver.com
    password: rhdwjd1968!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  jpa:
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/board?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: Rhdwjd1968!

jwt:
  secret: AAAABBBBCCCCDDDDEEEEFFFFGGGG123!@#